// Ambient shape for the wasm-bindgen output in src/wasm/, generated by
// `npm run build:wasm` from crate/ and gitignored (not hand-authored).
declare module "./wasm/signal_jam_core.js" {
  export default function init(
    module_or_path?: RequestInfo | URL | Response | BufferSource | WebAssembly.Module,
  ): Promise<void>;
  export function greet(): string;
}
